### ISSUE TITLE
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain

### ISSUE THREAD

**Issue by jenilkanani** [taxjar/taxjar-php#13]
Hello, 
I am trying to install the taxjar-php by following instruction from https://developers.taxjar.com/api/guides/php/#php-quickstart 
I am facing the below error:

`Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\wamp\www\project_research\taxjar-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\wamp\www\project_research\taxjar-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\wamp\www\project_research\taxjar-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\wamp\www\project_research\taxjar-php\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHtt in C:\wamp\www\project_research\taxjar-php\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187`

I tried to enable SSL to my localhost but no luck. Please help me to get out of this issue.
Thanks
JenilK

**Comment by fastdivision** [comment]
Hi @jenilkanani,

You may need to update your bundle of CA root certificates locally. Find out where PHP is looking for certs:

```php
var_dump(openssl_get_cert_locations());
```

If you're on a Mac you can use Homebrew to install OpenSSL with the necessary PEM file and update your `php.ini` configuration file: http://stackoverflow.com/a/31253824/6924224

Otherwise download the `cacert.pem` file at https://curl.haxx.se/docs/caextract.html and update your `php.ini` file with the path: 

```
curl.cainfo = <absolute_path_to> cacert.pem
```

These Stack Overflow threads provide more info:

http://stackoverflow.com/questions/29822686/curl-error-60-ssl-certificate-unable-to-get-local-issuer-certificate
http://stackoverflow.com/questions/21187946/60-ssl-certificate-self-signed-certificate-in-certificate-chainbool

**Comment by jenilkanani** [comment]
Upgrading the WAMP to higher version resolved my issue. 

Thanks for your time.
