### ISSUE TITLE
Sales orders list end-point returns invalid results

### ISSUE THREAD

**Issue by baatractive** [taxjar/taxjar-php#45]
According to the documentation the `transactions/orders` should return a list of the order numbers but rather it returns a list of strings:

```
{
    "orders": [
        "with_sales_tax_order",
        "default"
    ]
}
``` 

![image](https://user-images.githubusercontent.com/88047235/143908928-ceba0333-7a6d-4718-b08d-90bfbca4474e.png)

**Comment by sethobey** [comment]
Hi @baatractive,

I'm not sure I understand this issue. The screenshots you've provided show a Postman response from one of the TaxJar APIs, which isn't directly related to the code in this repository.

If you're sharing that Postman result because you happen to be using our taxjar-php SDK and those identifiers are what you're seeing in TaxJar, I'd suggest investigating what [`transaction_id` value is being included in the original "create" request](https://developers.taxjar.com/api/reference/?php#post-create-an-order-transaction).

Our API allows a user-defined string to be passed as the unique identifier for orders and refunds, so in the example you've provided, "with_sales_tax_order" and "default" would be order IDs of two separate transactions.

Take a look a these results in Postman...
![image](https://user-images.githubusercontent.com/47947793/144167337-4ae12975-01ba-4023-9221-60d81ef96f60.png)
![image](https://user-images.githubusercontent.com/47947793/144167890-d81fc117-2b18-4282-a5e1-a85a299e8f33.png)

...and the corresponding transactions when viewed in TaxJar.
![image](https://user-images.githubusercontent.com/47947793/144167966-594fca6c-5846-49b9-9d57-b4ba44a355e7.png)

If you need any further assistance, please reach out to our support team at support@taxjar.com or [visit our support center](https://support.taxjar.com).
